
name: test-arsenal

on: [push]

jobs:
  test-arsenal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Arsenal
      run: |
        sudo ./arsenal.sh container
